train_clean_wave_path: "/not_provide"
train_noisy_wave_path: "/not_provide"
clean_wave_path: "/Work/audio_algo/zy/Corpus/RNN_NOISE_DATA/clean_testset_wav"
noisy_wave_path: "/Work/audio_algo/zy/Corpus/RNN_NOISE_DATA/noisy_testset_wav"
dummy_input: [[480], [44344], [1]]
batch_size: 1
channel: 1
height: 42
width: 1
fp32_min: -41.1027
fp32_max: 41.2633
