model_fp32: /model_fp32.pickle
model_fp32_pth: /model_fp32.pth
size0: 3
size1: 224
size2: 224
bits_weight: 8
bits_activation: 8
bits_bias: 32
per_channel: false
w_symmetry: true
a_symmetry: false
sft_based: false
forge: true
Bcompensation: false
signed_e: true
Wcompensation: false
isReLU6: false
calibration: true
qat: false
model_quant_path: /quant_model.pth
preshift_path: None
fp32_min: -2.1179
fp32_max: 2.64
acc_quant: 76.03
acc_backend: 76.076
# acc_c_backend:0.76068